# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: jhossedmolina
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: aws-lambda-pokedex-app
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-lambda-pokedex-app

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:897722674489:table/PokemonTable

functions:
  getPokemons:
    handler: src/getPokemons.getPokemons
    events:
      - httpApi:
          path: /getPokemons
          method: get
  capturePokemon:
    handler: src/capturePokemon.capturePokemon
    events:
      - httpApi:
          path: /capturePokemon
          method: post
        

resources:
  Resources:
    ToDoTaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PokemonTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
